controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\testController::index

#account:
#  path: /account
#  controller: App\Controller\userController::account

#createAccount:
#  path: /create-account
#  controller: App\Controller\userController::new

#product:
#  path: /product
#  controller: App\Controller\dealController::product

#createProduct:
#  path: /create-product
#  controller: App\Controller\dealController::new

#allProducts:
#  path: /all-products
#  controller: App\Controller\dealController::allProducts
