<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxRmW5v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxRmW5v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxRmW5v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxRmW5v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxRmW5v\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxRmW5v',
    'container.build_id' => 'd17448b3',
    'container.build_time' => 1665060264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxRmW5v');
