<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOJe78zo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOJe78zo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOJe78zo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOJe78zo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOJe78zo\App_KernelDevDebugContainer([
    'container.build_hash' => 'OJe78zo',
    'container.build_id' => '5cf6ae06',
    'container.build_time' => 1666024760,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOJe78zo');
