<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMqLKIkm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMqLKIkm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMqLKIkm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMqLKIkm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMqLKIkm\App_KernelDevDebugContainer([
    'container.build_hash' => 'MqLKIkm',
    'container.build_id' => 'b1515a1d',
    'container.build_time' => 1665068504,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMqLKIkm');
